// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeiFeira.Infrastructure.Data;

#nullable disable

namespace PeiFeira.Infrastructure.Migrations
{
    [DbContext(typeof(PeiFeiraDbContext))]
    [Migration("20251012191830_CorrecaoNavegacaoOrfa")]
    partial class CorrecaoNavegacaoOrfa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeiFeira.Domain.Entities.Avaliacoes.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AvaliadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClarezaApresentacao")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("DominioAssunto")
                        .HasColumnType("int");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FocoSolucao")
                        .HasColumnType("int");

                    b.Property<int>("FundamentacaoProblema")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LinguagemTempo")
                        .HasColumnType("int");

                    b.Property<decimal?>("NotaFinal")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("PadronizacaoApresentacao")
                        .HasColumnType("int");

                    b.Property<decimal?>("PontuacaoTotal")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QualidadeRespostas")
                        .HasColumnType("int");

                    b.Property<int>("RelevanciaProblema")
                        .HasColumnType("int");

                    b.Property<int>("TransmissaoInformacoes")
                        .HasColumnType("int");

                    b.Property<int>("ViabilidadeSolucao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvaliadorId");

                    b.HasIndex("IsActive");

                    b.HasIndex("NotaFinal");

                    b.HasIndex("EquipeId", "AvaliadorId")
                        .IsUnique()
                        .HasDatabaseName("IX_Avaliacao_Equipe_Avaliador_Unique");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.DisciplinasPI.DisciplinaPI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Objetivos")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PerfilProfessorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PerfilProfessorId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SemestreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TemaGeral")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PerfilProfessorId");

                    b.HasIndex("PerfilProfessorId1");

                    b.HasIndex("SemestreId");

                    b.ToTable("DisciplinaPI");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.DisciplinasPI.DisciplinaPITurma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DisciplinaPIId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TurmaId");

                    b.HasIndex("DisciplinaPIId", "TurmaId")
                        .IsUnique()
                        .HasDatabaseName("IX_DisciplinaPITurma_Disciplina_Turma_Unique");

                    b.ToTable("DisciplinaPITurma");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Equipes.ConviteEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConvidadoPerfilAlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConvidadoPorPerfilAlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivoResposta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RespondidoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConvidadoPerfilAlunoId");

                    b.HasIndex("ConvidadoPorPerfilAlunoId");

                    b.HasIndex("Status");

                    b.HasIndex("EquipeId", "ConvidadoPerfilAlunoId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConviteEquipe_Equipe_Convidado_Unique");

                    b.ToTable("ConviteEquipe");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Equipes.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodigoConvite")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LiderPerfilAlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrlQrCode")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoConvite")
                        .IsUnique()
                        .HasFilter("[CodigoConvite] IS NOT NULL");

                    b.HasIndex("IsActive");

                    b.HasIndex("LiderPerfilAlunoId");

                    b.HasIndex("ProjetoId")
                        .IsUnique();

                    b.ToTable("Equipe");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Equipes.MembroEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Funcao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("IngressouEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PerfilAlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SaiuEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("PerfilAlunoId", "EquipeId", "IsActive")
                        .HasDatabaseName("IX_MembroEquipe_PerfilAluno_Equipe_Active");

                    b.ToTable("MembroEquipe");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Projetos.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CargoResponsavel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesafioProposto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("DisciplinaPIId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailResponsavel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EnderecoCompleto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeResponsavel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RedeSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RedesSociaisResponsavel")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TelefoneResponsavel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaPIId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Status");

                    b.ToTable("Projeto", (string)null);
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Semestres.Semestre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Ano", "Periodo")
                        .IsUnique();

                    b.ToTable("Semestre");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Turmas.AlunoTurma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAtual")
                        .HasColumnType("bit");

                    b.Property<Guid>("PerfilAlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TurmaId");

                    b.HasIndex("PerfilAlunoId", "TurmaId", "IsAtual");

                    b.ToTable("AlunosTurma");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Turmas.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Curso")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Periodo")
                        .HasColumnType("int");

                    b.Property<Guid>("SemestreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Turno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("SemestreId");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Usuarios.PerfilAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Curso")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Turno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilAluno");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Usuarios.PerfilProfessor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AreaEspecializacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departamento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Titulacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilProfessor");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Avaliacoes.Avaliacao", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.Usuarios.Usuario", "Avaliador")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeiFeira.Domain.Entities.Equipes.Equipe", "Equipe")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliador");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.DisciplinasPI.DisciplinaPI", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.Usuarios.PerfilProfessor", "Professor")
                        .WithMany()
                        .HasForeignKey("PerfilProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeiFeira.Domain.Entities.Usuarios.PerfilProfessor", null)
                        .WithMany("DisciplinasProfessor")
                        .HasForeignKey("PerfilProfessorId1");

                    b.HasOne("PeiFeira.Domain.Entities.Semestres.Semestre", "Semestre")
                        .WithMany()
                        .HasForeignKey("SemestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.DisciplinasPI.DisciplinaPITurma", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.DisciplinasPI.DisciplinaPI", "DisciplinaPI")
                        .WithMany("DisciplinaPITurmas")
                        .HasForeignKey("DisciplinaPIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeiFeira.Domain.Entities.Turmas.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DisciplinaPI");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Equipes.ConviteEquipe", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.Usuarios.PerfilAluno", "Convidado")
                        .WithMany()
                        .HasForeignKey("ConvidadoPerfilAlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeiFeira.Domain.Entities.Usuarios.PerfilAluno", "ConvidadoPor")
                        .WithMany()
                        .HasForeignKey("ConvidadoPorPerfilAlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeiFeira.Domain.Entities.Equipes.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convidado");

                    b.Navigation("ConvidadoPor");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Equipes.Equipe", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.Usuarios.PerfilAluno", "Lider")
                        .WithMany()
                        .HasForeignKey("LiderPerfilAlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeiFeira.Domain.Entities.Projetos.Projeto", "Projeto")
                        .WithOne("Equipe")
                        .HasForeignKey("PeiFeira.Domain.Entities.Equipes.Equipe", "ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lider");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Equipes.MembroEquipe", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.Equipes.Equipe", "Equipe")
                        .WithMany("Membros")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeiFeira.Domain.Entities.Usuarios.PerfilAluno", "PerfilAluno")
                        .WithMany("MembroEquipes")
                        .HasForeignKey("PerfilAlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("PerfilAluno");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Projetos.Projeto", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.DisciplinasPI.DisciplinaPI", "DisciplinaPI")
                        .WithMany("Projetos")
                        .HasForeignKey("DisciplinaPIId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DisciplinaPI");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Turmas.AlunoTurma", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.Usuarios.PerfilAluno", "PerfilAluno")
                        .WithMany("Turmas")
                        .HasForeignKey("PerfilAlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeiFeira.Domain.Entities.Turmas.Turma", "Turma")
                        .WithMany("AlunosTurma")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Turmas.Turma", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.Semestres.Semestre", "Semestre")
                        .WithMany("Turmas")
                        .HasForeignKey("SemestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Usuarios.PerfilAluno", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithOne("PerfilAluno")
                        .HasForeignKey("PeiFeira.Domain.Entities.Usuarios.PerfilAluno", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Usuarios.PerfilProfessor", b =>
                {
                    b.HasOne("PeiFeira.Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithOne("PerfilProfessor")
                        .HasForeignKey("PeiFeira.Domain.Entities.Usuarios.PerfilProfessor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.DisciplinasPI.DisciplinaPI", b =>
                {
                    b.Navigation("DisciplinaPITurmas");

                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Equipes.Equipe", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Projetos.Projeto", b =>
                {
                    b.Navigation("Equipe")
                        .IsRequired();
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Semestres.Semestre", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Turmas.Turma", b =>
                {
                    b.Navigation("AlunosTurma");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Usuarios.PerfilAluno", b =>
                {
                    b.Navigation("MembroEquipes");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Usuarios.PerfilProfessor", b =>
                {
                    b.Navigation("DisciplinasProfessor");
                });

            modelBuilder.Entity("PeiFeira.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("PerfilAluno");

                    b.Navigation("PerfilProfessor");
                });
#pragma warning restore 612, 618
        }
    }
}
